---
- name: create backend directory on EC2
  become: yes
  file:
    path: /home/ubuntu/backend
    state: directory
    # set file mode to 0755 -> https://chmodcommand.com/chmod-0755/ 
    mode: 0755

- name: copy files to backend
  become: yes
  copy: 
    src: artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz

- name: unzip backend directory
  become: yes
  shell: |
    cd /home/ubuntu/backend
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz
- name: start application
  become: yes
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
    
- name: print environment variables
  become: yes
  shell: |
    printenv
  register: printenv_out

